# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laji',
            name='kilpailu',
        ),
        migrations.AddField(
            model_name='kilpailu',
            name='kisaaja',
            field=models.ManyToManyField(to='kisa.Kisaaja'),
        ),
        migrations.AddField(
            model_name='kilpailu',
            name='laji',
            field=models.ManyToManyField(to='kisa.Laji'),
        ),
    ]
