# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 14:13
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kisa', '0002_auto_20170510_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='AikaLaji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aika', models.DurationField(default=0)),
                ('nimi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kisa.Laji')),
            ],
        ),
        migrations.CreateModel(
            name='KisaIlmo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LajiKierros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kierros_numero', models.IntegerField(default=0)),
                ('laji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisa.Laji')),
            ],
        ),
        migrations.CreateModel(
            name='Pistelaji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pisteet', models.IntegerField(default=0)),
                ('nimi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kisa.Laji')),
            ],
        ),
        migrations.CreateModel(
            name='TulosLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pisteet', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelManagers(
            name='kilpailu',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='kisaaja',
            name='ruoka_allergiat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tuloslista',
            name='kilpailija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisa.Kisaaja'),
        ),
        migrations.AddField(
            model_name='tuloslista',
            name='kilpailu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisa.Kilpailu'),
        ),
        migrations.AddField(
            model_name='tuloslista',
            name='lajipisteet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisa.LajiPisteet'),
        ),
        migrations.AddField(
            model_name='kisailmo',
            name='kilpailu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisa.Kilpailu'),
        ),
        migrations.AddField(
            model_name='kisailmo',
            name='kisaaja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisa.Kisaaja'),
        ),
    ]
