# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisa', '0003_auto_20170513_1413'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kilpailu',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='kisaaja',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
    ]
